sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate
script:
  - pep8 sis_provisioner/ --exclude=migrations,resources
  - rm -rf /tmp/fl_test/*
  - python -m compileall sis_provisioner
  - coverage run --source=sis_provisioner --omit=sis_provisioner/migrations/*,sis_provisioner/resources/* manage.py test sis_provisioner
after_script:
  - coveralls
