sudo: false
language: python
python:
  - "3.6"

before_script:
  - pip install -e .
  - pip install pycodestyle
  - pip install coverage
  - pip install commonconf
  - pip install coveralls
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate

script:
  - pycodestyle sis_provisioner/ --exclude=migrations,resources
  # - rm -rf /tmp/fl_test/*
  - rm -f /tmp/gwsuser*
  - python -m compileall sis_provisioner
  - coverage run --source=sis_provisioner --omit=sis_provisioner/migrations/*,sis_provisioner/resources/* manage.py test sis_provisioner

after_script:
  - coveralls
