# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('netid', models.SlugField(max_length=32, unique=True)),
                ('last_visited_date', models.DateTimeField()),
                ('import_priority', models.SmallIntegerField(choices=[(0, b'none'), (1, b'normal'), (2, b'high'), (3, b'regid changed'), (4, b'netid changed')], default=1)),
                ('terminate_date', models.DateTimeField(null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64, null=True)),
                ('is_alum', models.NullBooleanField()),
                ('is_employee', models.NullBooleanField()),
                ('is_faculty', models.NullBooleanField()),
                ('is_staff', models.NullBooleanField()),
                ('is_student', models.NullBooleanField()),
                ('student_department1', models.CharField(max_length=255, null=True)),
                ('student_department2', models.CharField(max_length=255, null=True)),
                ('student_department3', models.CharField(max_length=255, null=True)),
                ('emp_appointments_data', models.TextField(max_length=2048, null=True)),
            ],
            options={
                'db_table': 'uw_bridge_users',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_number', models.PositiveSmallIntegerField()),
                ('job_class_code', models.CharField(max_length=96)),
                ('org_code', models.CharField(max_length=16)),
            ],
        ),
    ]
