# Generated by Django 3.2.19 on 2023-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UwAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.SlugField(unique=True)),
                ('prev_netid', models.SlugField(default=None, null=True)),
                ('bridge_id', models.IntegerField(db_index=True, default=0)),
                ('employee_id', models.SlugField(default=None, max_length=10, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(default=None, null=True)),
                ('terminate_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'uwuseraccounts',
            },
        ),
    ]
