# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeUser',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('netid', models.SlugField(max_length=32, unique=True)),
                ('regid', models.CharField(db_index=True,
                                           max_length=32, unique=True)),
                ('last_visited_date', models.DateTimeField()),
                ('last_import_date', models.DateTimeField(null=True)),
                ('last_import_err', models.CharField(max_length=10,
                                                     null=True)),
                ('terminate_date', models.DateTimeField(null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(max_length=128, blank=True)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64, null=True)),
                ('is_alum', models.NullBooleanField()),
                ('is_employee', models.NullBooleanField()),
                ('is_faculty', models.NullBooleanField()),
                ('is_staff', models.NullBooleanField()),
                ('is_student', models.NullBooleanField()),
                ('student_department1', models.CharField(max_length=255,
                                                         null=True)),
                ('student_department2', models.CharField(max_length=255,
                                                         null=True)),
                ('student_department3', models.CharField(max_length=255,
                                                         null=True)),
                ('hrp_home_dept_org_code', models.CharField(max_length=16,
                                                            null=True)),
                ('hrp_home_dept_org_name', models.CharField(max_length=96,
                                                            null=True)),
                ('hrp_job_class_code', models.CharField(max_length=16,
                                                        null=True)),
                ('hrp_job_class_title', models.CharField(max_length=96,
                                                         null=True)),
                ('hrp_emp_status', models.CharField(max_length=2,
                                                    null=True)),
            ],
            options={
                'db_table': 'uw_bridge_users',
            },
        ),
    ]
