# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_number', models.PositiveSmallIntegerField()),
                ('job_class_code', models.CharField(max_length=96)),
                ('org_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UwBridgeUser',
            fields=[
                ('regid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('bridge_id', models.IntegerField(default=0)),
                ('netid', models.SlugField(max_length=32, unique=True)),
                ('prev_netid', models.SlugField(default=None, max_length=32, null=True)),
                ('email', models.CharField(default=None, max_length=128, null=True)),
                ('display_name', models.CharField(default=None, max_length=256, null=True)),
                ('first_name', models.CharField(default=None, max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128)),
                ('action_priority', models.SmallIntegerField(choices=[(0, b'none'), (1, b'add new'), (2, b'update'), (3, b'change regid'), (4, b'restore')], default=0)),
                ('disabled', models.NullBooleanField(default=False)),
                ('last_visited_at', models.DateTimeField()),
                ('terminate_at', models.DateTimeField(default=None, null=True)),
                ('is_employee', models.NullBooleanField(default=None)),
                ('emp_appointments_data', models.TextField(blank=True, default=None, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'uw_bridge_users',
            },
        ),
    ]
