# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwbridgeuser',
            name='bridge_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
