# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeuser',
            name='prev_netid',
            field=models.SlugField(max_length=32, null=True),
        ),
    ]
