# Generated by Django 2.0.13 on 2019-03-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0002_auto_20161228_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwbridgeuser',
            name='action_priority',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'add new'), (2, 'update'), (3, 'change regid'), (4, 'restore')], default=0),
        ),
    ]
