# Generated by Django 2.0.13 on 2019-03-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0003_auto_20190323_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='UwAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_id', models.IntegerField(db_index=True, default=0)),
                ('netid', models.SlugField(unique=True)),
                ('prev_netid', models.SlugField(default=None, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField()),
                ('terminate_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'uwuseraccounts',
            },
        ),
    ]
