# Generated by Django 2.0.13 on 2019-04-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0004_uwaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwaccount',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
