# Generated by Django 2.0.13 on 2019-04-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0005_auto_20190408_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAppointment',
        ),
        migrations.DeleteModel(
            name='UwBridgeUser',
        ),
    ]
