# Generated by Django 2.0.13 on 2019-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0006_auto_20190410_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='uwaccount',
            name='employee_id',
            field=models.SlugField(default=None, max_length=10, null=True),
        ),
    ]
